### ISSUE TITLE
When using non-English characters in the text parameter, encode does not occur

### ISSUE THREAD

**Issue by MrPandir** [twirapp/silero-tts-api-server#11]
```bash
curl -v 'localhost:8000/generate?speaker=aidar&text=тест'
> GET /generate?speaker=aidar&text=тест HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< content-type: text/plain; charset=utf-8
< Connection: close
Invalid HTTP request received.
```
It works:
```bash
curl -v 'http://localhost:8000/generate?speaker=aidar&text=%D1%82%D0%B5%D1%81%D1%82' --output test.wav
> GET /generate?speaker=aidar&text=%D1%82%D0%B5%D1%81%D1%82 HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Wed, 21 Feb 2024 17:47:56 GMT
< server: uvicorn
< content-type: audio/wav
< content-length: 43244
```

I'm not sure if this should be fixed at all 🤔
And is it possible to do this in uvicorn?

**Comment by crashmax-dev** [comment]
@MrPandir Why not use POST request?

**Comment by MrPandir** [comment]
One of the problems with using `POST` is how Swagger UI inserts audio into the interface, which I use for auto-documentation endpoints and for quick and easy manual testing.
https://github.com/swagger-api/swagger-ui/issues/8378

There is also a difference between using `POST` and `GET`. `GET` requests can be cached by the browser, which is an advantage.

This problem seems impossible to fix using `GET`. Maybe I'll add support for `POST` request

**Comment by MrPandir** [comment]
This is not a `litestar` or `uvicorn` problem. And the lack of decoding in the curl request. To fix this you need to make the following request:
```bash
curl -G 'http://localhost:8000/generate' --data-urlencode 'text=тест' --data-urlencode 'speaker=aidar' --output test.wav
```
